// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://doivydlgznehzxhjksnv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRvaXZ5ZGxnem5laHp4aGprc252Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg0NDA4NzEsImV4cCI6MjA1NDAxNjg3MX0.N0oBzDbz8wpNz1kAoC99EpB9Xcd9KNPQYiR5vwqPqc0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});